name: demoback
server:
  port: 80
spring:
  #Jersey配置
  jersey:
    application-path: /
    #resource-package: com.pvsoul.demo.resouce
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    date-format: yyyy-MM-dd HH:mm:ss
    parser:
      allow-missing-values: true
#log日志配置
logging:
  level:
    root: info